name: Business Dash CI Coverage

on:
    workflows: ["*CI*"]
    types:
      - completed

jobs:
  business-dashboard-ui:
    uses: pwei1018/bcregistry-sre/.github/workflows/frontend-ci-coverage.yaml@main
