name: Business Dash CI

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  business-dashboard-ui:
    uses: pwei1018/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "business-dashboard-ui"
      working_directory: "."